### ISSUE TITLE
SUPER BAD BUG

### ISSUE THREAD

**Issue by Mcdoodle20** [Sequitur-Studios/Cell-Machine-Mystic-Mod#102]
**BASICALY** I have been not able to do anything because of this stupid bug. My camera is always going up-left . **Please** fix this

**Comment by Imlxgit** [comment]
i dont think this is a bug with the game. this is most likely caused by your keyboard

**Comment by TheMysticLynx** [comment]
This is not proper format for a bug report. We need steps to reproduce, it's very likely this is a issue with a connected gamepad or keyboard and not with the game. Can you give us more details? Does this happen after restarting the computer?

**Comment by itskegnh** [comment]
**What this may be caused by:**
Issues like this are often caused by the computer, most of the time it acts as sticky keys.
To fix, try press the key for the direction, just a quick tap, and it should stop it from being simulated held down.

**Comment by TheMysticLynx** [comment]
Closing due to no response from original poster
