### ISSUE TITLE
Subticking shows ticks at normal speed

### ISSUE THREAD

**Issue by Imlxgit** [Sequitur-Studios/Cell-Machine-Mystic-Mod#103]
This is a problem and a feature. Not a big problem, just a small one. Anywho, when you turn on subticking, the tick counter shows the amount of ticks that _should_ have passed if subticking wasn't on.

Pretty sure this would be a breeze to fix so it would be pretty cool :)

**Comment by TheMysticLynx** [comment]
This was intentional so you can keep track of subticks as well. For example giving a bug report this would be useful because you can specify specific steps during subticking!

**Comment by Imlxgit** [comment]
ok

**Comment by SnazzGass** [comment]
Mystic: It's not a bug, It's a feature!

I also see this behavior as confusing, I think It would be better if we added a subtick number after the tick number. For instance **4:9** would be the 9th subtick in the 4th simulation tick
