### ISSUE TITLE
Debug panel in the corner is still in the game

### ISSUE THREAD

**Issue by ip36** [Sequitur-Studios/Cell-Machine-Mystic-Mod#105]
Press ` (on windows) to open the debug panel. Not sure if this is intentional but most games/projects remove debug buttons before releasing to the pubic
![image](https://user-images.githubusercontent.com/88632919/128645107-78c30693-a753-41c9-b54b-a3cd5b6ee2de.png)

**Comment by Alpha2-5232** [comment]
It is a feature and has a useful tool (the speed changer). This is not a bug.

**Comment by TheMysticLynx** [comment]
Won't be removed,
