### ISSUE TITLE
Jelly cell

### ISSUE THREAD

**Issue by ChivalricMender** [Sequitur-Studios/Cell-Machine-Mystic-Mod#108]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
a jelly cell will stick to other jelly cells.

**Describe alternatives you've considered**
This IS an alternative solution! It could replace sticky cell

**Additional context**
can't be rotated and can only get smaller by being pushed into a trash or enemy cell.

**Comment by uku1928** [comment]
No new cells.
