### ISSUE TITLE
Flip Key

### ISSUE THREAD

**Issue by PJG2O1O** [Sequitur-Studios/Cell-Machine-Mystic-Mod#119]
**Is your feature request related to a problem? Please describe.**

It is sometimes annoying not being able to flip objects.

**Describe the solution you'd like**

I would like a flip key to be added. Maybe you could press F when you have a copied thing, and it will flip it. You can kind of do this by rotating it twice, but I mean it would go from a K to a backwards K.

**Describe alternatives you've considered**

Maybe instead of having a flip key, you could select an area and there would be a button beside the delete button that is a rotator and it will flip it.

**Additional context**

Example is here ;
![image](https://user-images.githubusercontent.com/89023670/129571060-1b4cbb8a-d1c0-4d5d-a0ae-e7dd6788244a.png)
This is the end of my suggestion.

**Comment by uku1928** [comment]
Something similar was suggested in issue #91

**Comment by TheMysticLynx** [comment]
Duplicate.
