### ISSUE TITLE
Mildly infuriating texture glitch

### ISSUE THREAD

**Issue by uku1928** [Sequitur-Studios/Cell-Machine-Mystic-Mod#120]
**Bug description**
I cannot unsee these thin lines that appear when highlighting something.

**To Reproduce**
NOTE: You need a texture pack that has a good contrast difference between the one pixel outer edges of the cell and the pixels that touch the outer edges (You'll see what I mean with a picture). It can be a bit clearer with a lower resolution texture pack, but not a 2x2 or 1x1 pack.

1. Go to level editor
2. Place a cell
3. Highlight it.

**Expected behavior**
The entire outer edge of the cell gets highlighted, leaving no weird lines.

**Additional context / media**
The highlighter always highlights the 1-pixel wide border of the cell. The following picture was taken using a 5x5 texture pack that I made.
![image](https://user-images.githubusercontent.com/86157399/129856792-854b79e6-3c7d-4ec5-959d-fcd2ae119605.png)
Normal cell on left, highlighted on right.

**Comment by blaumeise20** [comment]
I would say the highlight border should have a fixed width, because it can be annoying with 2x2 packs (like my Better Artist pack) or with high resolution packs.
1. Low resolution: you don't see most of the textures
2. High resolution: you don't even see a border
