### ISSUE TITLE
Default texture pack is unselected by default

### ISSUE THREAD

**Issue by SnazzGass** [Sequitur-Studios/Cell-Machine-Mystic-Mod#21]
This leaves the background tiles completely transparent until you select the default texture pack. It seems to only affect standalone 
builds, not the unity player.

**Comment by jjblock21** [comment]
And I somehow managed to permanently get a texture from a texture pack to get stuck, Idk how to reproduce it though.

**Comment by f1shy-dev** [comment]
If you are on the latest commit(s), this issue should have been fixed.
