### ISSUE TITLE
Relicensing

### ISSUE THREAD

**Issue by bs2kbs2k** [Sequitur-Studios/Cell-Machine-Mystic-Mod#25]
[As Creative Commons is *not* intended for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), it would be nice to relicense this software to another, more software-specific license like GPLv3.

**Comment by TheMysticLynx** [comment]
New license should not allow the commercial use of the project. @SnazzGass

**Comment by w1wwwwww** [comment]
if the project is open source no one should be using this for commercial purposes anyway. "CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software." this means that someone could use the code in this project for commercial use as only art assets and such are protected under a CC license

**Comment by shahoob** [comment]
I think that's supposed to be a pull request.

**Comment by bs2kbs2k** [comment]
Why would you want to disallow commercial use? GPL doesn't explicitly disallow commercial use but it requires the person to release the modified source code to the users with the same license.

**Comment by w1wwwwww** [comment]
i think this can be closed due to #43
