### ISSUE TITLE
Suggestion: Coloured Cells

### ISSUE THREAD

**Issue by gdt2k** [Sequitur-Studios/Cell-Machine-Mystic-Mod#28]
I think this would be a cool thing to add because:
- You can colour code parts of a vault
- You can make cell machine art without a custom texture pack
How this would work
- Coloured Cells would use HSV to specify a colour
- Shift-click when selecting a cell (or use Z) to change its colour
- Then place the cells as you would normally
Cons
- Codes would need to store more data for each cell
- I see it taking a long time to program

**Comment by TheMysticLynx** [comment]
I don't see any major advantage of adding thing into the game. Every cell being the same texture makes levels very easily readable and a large focus of the editor has always been to make levels readable. We're also trying to keep level codes as simple as possible.
