### ISSUE TITLE
(feature) Sizeable cell

### ISSUE THREAD

**Issue by yesbecauseyes** [Sequitur-Studios/Cell-Machine-Mystic-Mod#29]
sizeable cell would be a cell that is a mover but can fit through other cells (expect slider and immovable cell). the sizeable cell can also be changed to be a slider cell. if something passes near it (like 10 cell long radius) then sizeable cell (now as slider cell version) would stretch 10 cells from the sides, blocking the passing cell that tries to pass sizeable cell radius. to change the modes, simply click again on the sizeable cell while building another sizeable cell
the cell idea what it could do (very questionable but dont worry, i just suck at drawing):
![do not ask](https://user-images.githubusercontent.com/84185103/126812755-4c63b9af-888e-45b6-8aac-9c3fd66d00ee.png)

**Comment by TheMysticLynx** [comment]
We have no plans of adding new cells to the game; Especially before the lua modding release.
