### ISSUE TITLE
When you move the debug menu you also unexpectedly place cells

### ISSUE THREAD

**Issue by gdt2k** [Sequitur-Studios/Cell-Machine-Mystic-Mod#31]
When you move the debug menu, the game thinks you're placing cells.

You can reproduce this by pressing ` to activate the debug menu and moving it around while a cell is selected. As far as I know, this only happens with:
- Trash Cells
- Enemy Cells
- Slide Cells
- Mover Cells
- Push Cells
- Generator Cells
- Both Rotator Cells
I'm sure this bug works with other cells too, but I haven't tried it yet.

When you move the debug menu around, it isn't supposed to place cells as well.

Here is a screenshot of the bug: (Texture pack used: Adobe Mystic Mod V3)
![image](https://user-images.githubusercontent.com/81596206/126820043-a9751060-e158-475a-b2d2-38121a0c9283.png)

As far as I know, this bug only works on A3.3.2.0.

**Comment by AppaBTW** [comment]
yo this type of stuff happened on my scratch remake a bunch of times

**Comment by TheMysticLynx** [comment]
Because of the way the debug UI is shown (Using the active gui system in unity) it's harder to check if the user is clicked into or not. This likely won't be fixed until (and if) a new debug gui is made.
