### ISSUE TITLE
Wrong placeable texture

### ISSUE THREAD

**Issue by uku1928** [Sequitur-Studios/Cell-Machine-Mystic-Mod#32]
This bug makes the wrong texture for placeables to appear.

**To Reproduce**
1. Open up the editor with any texture pack selected
2. Go back to main menu
3. Switch to a different texture pack
4. Open up the editor once again
5. Place a "placeable" background

**Expected behavior**
Placeable of the newly selected texture pack should appear

**Additional context / media**
Version: 3.3.2.0 (latest found on official Discord server)

![image](https://user-images.githubusercontent.com/86157399/126831336-dad9cc7b-3f2a-4fc5-86ea-0a2ff0799ff2.png)

**Comment by f1shy-dev** [comment]
This has been fixed in a commit since that release.
