### ISSUE TITLE
Option to hide buttons

### ISSUE THREAD

**Issue by TheTrashCell** [Sequitur-Studios/Cell-Machine-Mystic-Mod#36]
It would be nice if there was a shortcut to hide all the buttons on the screen (like Minecraft F1)
Could be useful when showing your levels and making videos.

**Comment by jjblock21** [comment]
I can try to fork it and do it. My last pull request didn't work out.

**Comment by uku1928** [comment]
We should close this issue

**Comment by TheMysticLynx** [comment]
#46
