### ISSUE TITLE
Issue/Missing Feature: Debug Menu Doesn't Reset

### ISSUE THREAD

**Issue by Alpha2-5232** [Sequitur-Studios/Cell-Machine-Mystic-Mod#38]
When using the debug menu, there is no way to reset it to the proper speed. One solution is to just add an Infinity/5 to the slider. Another solution is to add a snapping feature.

**Comment by TheMysticLynx** [comment]
Debug menu isn't considered a real part of the game. It's mostly used for quick testing and me and snazz won't be fixing bugs with it.
