### ISSUE TITLE
You sometimes have to click level gui twice.

### ISSUE THREAD

**Issue by jjblock21** [Sequitur-Studios/Cell-Machine-Mystic-Mod#41]
**Description**
The bug occurs when trying to open the Menu on the Level Screen. You have to click twice to open it, because in the Start() method the Menu gets hidden, but when the game gets compiled with it closed it immediately closes after being opened.

**To Reproduce**
Open it...

**Comment by BlockOG** [comment]
Yes, save button is the same thing

**Comment by jjblock21** [comment]
> Yes, save button is the same thing

Its for all the menu's, the exit button too, its a realy easy fix, either alter the scripts to not turn the object off in Start() or export the game with the gui active.

**Comment by jjblock21** [comment]
May attempt to fix this myself too.

**Comment by TheMysticLynx** [comment]
Fixed in latest commit.
