### ISSUE TITLE
brotli dlls not included in project

### ISSUE THREAD

**Issue by w1wwwwww** [Sequitur-Studios/Cell-Machine-Mystic-Mod#47]
the brotli dlls are not included with the project causing issues for devs. the dlls are blocked by the gitignore so an exeption may be able to be added

**Comment by f1shy-dev** [comment]
It seems they are git-ignored, I will make an exception for the Plugins folder and re-track the DLLs when I get time tomorrow. Sorry for the trouble.

**Comment by w1wwwwww** [comment]
thanks
