### ISSUE TITLE
Add a "Save selection as level code" button to the sandbox selection tool

### ISSUE THREAD

**Issue by ErikoX** [Sequitur-Studios/Cell-Machine-Mystic-Mod#50]
![Example](https://user-images.githubusercontent.com/54033728/126981652-501deb8d-bc95-49e8-8ca8-4e7cebe47642.png)

This would save time when making a custom level in a bigger grid than the level's size. You could then just select the built level and save it as a level code instantly, so you dont have to rebuild it on a smaller grid. (See example)

**Comment by TheMysticLynx** [comment]
Added!
