### ISSUE TITLE
Idea: Sticky Variants of Cells

### ISSUE THREAD

**Issue by ValkyrieXD** [Sequitur-Studios/Cell-Machine-Mystic-Mod#51]
In the discord is a emoji called :sticky: and all it does is to stick to cells

So i came up with Sticky Cell Variants:

1. Sticky Mover Cell 
All it does is move and everything it touches it moves with it. Even if something touches on its side it moves with it.

2. Sticky Rotator Cell 
Sam's scrapped idea.
If a cell touches it, it rotates with it. Kinda like a spinner.

3. Sticky Generator Cell 
If something is on the input, it can never be moved again.
If something pushes it, you can make a gun out of it.

Thats all but i think we can do more.
If nobody has joined the discord, heres what im talking about:
- The sticky cell can be like a box but if anything touches it, it will stay with it.

Idea by @ValkyrieXD

**Comment by jjblock21** [comment]
Mystic and Snazz already announced that they will not be adding new cells. also, so many new cells wouldn't quite fit in the game and if slime cells get added probably only the one everybody talks about.
