### ISSUE TITLE
Time scale??

### ISSUE THREAD

**Issue by GuyGuyGuyGuyGuyGuyGuyGuy** [Sequitur-Studios/Cell-Machine-Mystic-Mod#53]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
a time scale allowing to speed up the game process or slow it down, perhaps 

**Describe alternatives you've considered**

**Additional context**

**Comment by Alpha2-5232** [comment]
It already exists, press ` to open it

**Comment by f1shy-dev** [comment]
it already exists in the debug menu, as @Alpha2-5232 said.

**Comment by uku1928** [comment]
Close this issue
