### ISSUE TITLE
brotli compression is broken

### ISSUE THREAD

**Issue by w1wwwwww** [Sequitur-Studios/Cell-Machine-Mystic-Mod#56]
**Describe the bug**
brotli compression does not work and does not save

**To Reproduce**
make sure brotli compression is selected
try to save a level
in the unity console you will get a nullreference exeption

**Expected behavior**
the level actually saves properly

**Debug info**
the full error text from the unity console
`NullReferenceException: Object reference not set to an instance of an object
BrotliSharpLib.Brotli.FastLog2 (BrotliSharpLib.Brotli+SizeT v) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli.ShannonEntropy (System.UInt32* population, BrotliSharpLib.Brotli+SizeT size, BrotliSharpLib.Brotli+SizeT* total) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli.BitsEntropy (System.UInt32* population, BrotliSharpLib.Brotli+SizeT size) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli+CompressFragmentTwoPass.ShouldCompress (System.Byte* input, BrotliSharpLib.Brotli+SizeT input_size, BrotliSharpLib.Brotli+SizeT num_literals) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli+CompressFragmentTwoPass.BrotliCompressFragmentTwoPassImpl (BrotliSharpLib.Brotli+MemoryManager& m, System.Byte* input, BrotliSharpLib.Brotli+SizeT input_size, System.Boolean is_last, System.UInt32* command_buf, System.Byte* literal_buf, System.Int32* table, BrotliSharpLib.Brotli+SizeT table_bits, BrotliSharpLib.Brotli+SizeT* storage_ix, System.Byte* storage) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli+CompressFragmentTwoPass.BrotliCompressFragmentTwoPass (BrotliSharpLib.Brotli+MemoryManager& m, System.Byte* input, BrotliSharpLib.Brotli+SizeT input_size, System.Boolean is_last, System.UInt32* command_buf, System.Byte* literal_buf, System.Int32* table, BrotliSharpLib.Brotli+SizeT table_size, BrotliSharpLib.Brotli+SizeT* storage_ix, System.Byte* storage) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli.BrotliCompressFragmentTwoPass (BrotliSharpLib.Brotli+MemoryManager& m, System.Byte* input, BrotliSharpLib.Brotli+SizeT input_size, System.Boolean is_last, System.UInt32* command_buf, System.Byte* literal_buf, System.Int32* table, BrotliSharpLib.Brotli+SizeT table_size, BrotliSharpLib.Brotli+SizeT* storage_ix, System.Byte* storage) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli.BrotliEncoderCompressStreamFast (BrotliSharpLib.Brotli+BrotliEncoderStateStruct& s, BrotliSharpLib.Brotli+BrotliEncoderOperation op, BrotliSharpLib.Brotli+SizeT* available_in, System.Byte** next_in, BrotliSharpLib.Brotli+SizeT* available_out, System.Byte** next_out, BrotliSharpLib.Brotli+SizeT* total_out) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.Brotli.BrotliEncoderCompressStream (BrotliSharpLib.Brotli+BrotliEncoderStateStruct& s, BrotliSharpLib.Brotli+BrotliEncoderOperation op, BrotliSharpLib.Brotli+SizeT* available_in, System.Byte** next_in, BrotliSharpLib.Brotli+SizeT* available_out, System.Byte** next_out, BrotliSharpLib.Brotli+SizeT* total_out) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.BrotliStream.WriteCore (System.Byte[] buffer, System.Int32 offset, System.Int32 count, BrotliSharpLib.Brotli+BrotliEncoderOperation operation) (at <8abe3495f7f047ed822d11fb9d962483>:0)
BrotliSharpLib.BrotliStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) (at <8abe3495f7f047ed822d11fb9d962483>:0)
Compression.CopyTo (System.IO.Stream src, System.IO.Stream dest) (at Assets/Scripts/Classes/Compression.cs:16)
Compression.BrotliString (System.String str) (at Assets/Scripts/Classes/Compression.cs:26)
Save.SaveString () (at Assets/Scripts/Level Data/Save.cs:208)
UnityEngine.Events.InvokableCall.Invoke () (at <028e4d71153d4ed5ac6bee0dfc08aa3b>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <028e4d71153d4ed5ac6bee0dfc08aa3b>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:68)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:110)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:377)`

![image](https://user-images.githubusercontent.com/26696846/127396400-3cfdbf60-6f7c-4d3d-90aa-8b88f7fab033.png)

the error is in brotli itself and brotli compression should be removed or at least reconsidered

**Comment by w1wwwwww** [comment]
a stackoverflowexeption is also possible 
![image](https://user-images.githubusercontent.com/26696846/127401363-5f9140b3-d73a-43d4-9397-a7c869edfc70.png)

**Comment by f1shy-dev** [comment]
I'll take a look now, and try to switch out the libraries. If not, I'll remove V4 for now.
