### ISSUE TITLE
Texture pack descriptions and texture pack icons

### ISSUE THREAD

**Issue by AppaBTW** [Sequitur-Studios/Cell-Machine-Mystic-Mod#57]
hey i would like texture pack descriptions to be implemented in the game so the artists can describe what the pack is and display that they are the ones to make it.
i also would like icons for texture packs as only using names would be difficult to identify different packs so icons would solve that 
I have no idea how to make descriptions but maybe a file the game can read would work

**Comment by w1wwwwww** [comment]
texture pack icons are already implemented, i might add pack descriptions

**Comment by AppaBTW** [comment]
> texture pack icons are already implemented, i might add pack descriptions

what? how do u add them??

**Comment by w1wwwwww** [comment]
idk i just know that they are in the source code

**Comment by f1shy-dev** [comment]
I will make it more clear on how to do this soon (a tutorial or something).
