### ISSUE TITLE
Ability to make mods in mystic mod

### ISSUE THREAD

**Issue by ValkyrieXD** [Sequitur-Studios/Cell-Machine-Mystic-Mod#60]
### If Mystic dosen't want to implement more cells then we can
**To not call them mods, call them Datapacks, individual mods can be call datamods**

Mystic already works on that and its Lua,
this issue was just to make them a name because we already have a "mod"

**Comment by ValkyrieXD** [comment]
i think im closing this soon.....

**Comment by TheMysticLynx** [comment]
It'll be considered,
