### ISSUE TITLE
Friend cell

### ISSUE THREAD

**Issue by TJCgames** [Sequitur-Studios/Cell-Machine-Mystic-Mod#62]
I have an idea about a cell: the friend cell. It is the opposite of an enemy cell. If you destroy a friend cell, you lose. If you dont destroy any friend cells, you win.

**Comment by jerbear2008** [comment]
The devs are not going to implement new cells into the game. The game is open source, so if you want to make a version with them you can.

**Comment by TJCgames** [comment]
My coding skills: -999999999999999999999999999999999999999999999999999999999999999999999999999%

**Comment by TheMysticLynx** [comment]
New cells will not be added on the matter branch.
