### ISSUE TITLE
V3=V1

### ISSUE THREAD

**Issue by uku1928** [Sequitur-Studios/Cell-Machine-Mystic-Mod#64]
**Descrption of the bug**
People on Discord have been lately getting levels saved as V1 format from their levels even though they say they have V3 format

**To reproduce**
I haven't reproduced it myself as I already have a file that has saved settings, but I believe this is how it goes:
1. Make sure you don't have a file that has saved settings (?)
2. Download the latest version of Mystic Mod
3. Go to the level editor
4. Export the level

**To fix the bug**
1. Go to settings
2. Change the string format to V2
3. Export a level
4. (optional if you want to save as V3) Change the string format back to V3

**Expected behavior**
V3 codes get copied

**Media**
![image](https://user-images.githubusercontent.com/86157399/127765284-f6d2fb63-dcb1-4c76-8f70-f1dd606dfce7.png)
![image](https://cdn.discordapp.com/attachments/792373980199125032/871298060939042856/unknown.png)

**Comment by f1shy-dev** [comment]
I will investigate/fix this.
