### ISSUE TITLE
Include a Classic Texture Pack with the Default Pack (like Minecraft's Programmer Art)

### ISSUE THREAD

**Issue by Just-a-Unity-Dev** [Sequitur-Studios/Cell-Machine-Mystic-Mod#68]
**Describe the solution you'd like**
Include a Classic Pack with the original textures of the game

**Describe alternatives you've considered**
Manually installing it

**Additional context**
I want a classic pack since some people don't have Discord, like my friends, they contact me on Messenger and not on Discord because he uninstalled Authenticator

**Comment by AppaBTW** [comment]
there is no official version of the original cell machines textures so this would be difficult to implement

**Comment by Just-a-Unity-Dev** [comment]
there is, some guy ported the textures from the original Cell Machine, this wouldn't be too hard

**Comment by AppaBTW** [comment]
> there is, some guy ported the textures from the original Cell Machine, this wouldn't be too hard

actually, multiple people did,
that's the issue if one gets in the game others might be sad their version didn't get in and complain

**Comment by TheMysticLynx** [comment]
We don't have the rights to include those assets in our game.
