### ISSUE TITLE
how to use electron launcher

### ISSUE THREAD

**Issue by w1wwwwww** [Sequitur-Studios/Cell-Machine-Mystic-Mod#73]
how can i use the launcher? i dont know how to build electron apps

**Comment by f1shy-dev** [comment]
You can download it from github actions (but it wont work until mystic or any of the people with repo-write-access make a release as the launcher gets the versions of the game from github releases).

**Comment by w1wwwwww** [comment]
if i made releases on my fork and changed the references would it work?

**Comment by Just-a-Unity-Dev** [comment]
nope! as @f1shy-dev said, you can download it from github, but it wont work until Mystic makes a release on the github page

**Comment by f1shy-dev** [comment]
Yes, as for now it's hard-coded to this repo.

**Comment by f1shy-dev** [comment]
*Also right now we're having a LFS quota problem so I doubt the launcher will be built for the latest commits right now.
