### ISSUE TITLE
Broken sliders

### ISSUE THREAD

**Issue by uku1928** [Sequitur-Studios/Cell-Machine-Mystic-Mod#77]
**Bug description**
The sliders on the level editor options menu don't do anything

**To reproduce**
1. Go to level editor or play a level
2. Click on the menu button
3. Move the sliders around

**Expected behavior**
The sliders should change the percentage to the right of them

**Additional context / media**
![image](https://user-images.githubusercontent.com/86157399/127962257-b20eb889-f4bd-466e-abf8-1e3c4359aad1.png)
_Edit:_ When you go back to main menu then to level editor again, the sliders reset their position to rightmost
_Edit:_ V3.5.0.0 made moving the sliders actually change the volume of music but changing sound doesn't work.

**Comment by f1shy-dev** [comment]
For now use the ones in options, that is broken due to the script file changing name.

**Comment by uku1928** [comment]
Now that since a paid version came out and Mystic told it has quality of life changes, I'm assuming the qol changes include bug fixes
My point being: I will be closing all my "bug" issues.
