### ISSUE TITLE
broken music

### ISSUE THREAD

**Issue by astrohaha** [Sequitur-Studios/Cell-Machine-Mystic-Mod#79]
**Describe the bug**
music is gone

**To Reproduce**
wait for a bit

**Expected behavior**
music should be gone

**Comment by uku1928** [comment]
Expected behavior should be: "music should keep playing"

**Comment by uku1928** [comment]
Issue #80 describes the bug in more detail

**Comment by TheMysticLynx** [comment]
Duplicate
