### ISSUE TITLE
White box

### ISSUE THREAD

**Issue by uku1928** [Sequitur-Studios/Cell-Machine-Mystic-Mod#81]
**Bug description**
A white box appears in bottom-right corner when the game tries to import an invalid level

**To reproduce**
1. Copy a random string of text (Not a level code)
2. Go to play menu (The menu that comes up when pressing play on main menu)
3. Try to import a level

**Expected behavior**
Some text telling the error should appear instead

**Additional context / media**
![image](https://user-images.githubusercontent.com/86157399/127969807-81126a8f-cf42-4099-9b71-e02f6458be17.png)
When fading:
![image](https://user-images.githubusercontent.com/86157399/127969829-5c9dd95c-0e38-4397-b9a1-2c4080a21962.png)

**Comment by TheMysticLynx** [comment]
Fixed with removal of lfs.
