### ISSUE TITLE
Auto-Update System

### ISSUE THREAD

**Issue by ProFoxyfy** [Sequitur-Studios/Cell-Machine-Mystic-Mod#84]
I'm always frustrated having to download the mod's updates manually

so I want An update system that checks for updates and downloads them automatically at startup (Schedule feature in settings)

**Comment by itskegnh** [comment]
We already have proof of a launcher being added, In the main branch you can see a Launcher folder, not much is in it though and its not certain if it will ever be released, that being said a launcher would be very useful, but would take a lot of effort on the developers part.

**Comment by f1shy-dev** [comment]
The launcher already exists and technically works, we just haven't fully provided it to like the itch page yet.
