### ISSUE TITLE
A way (maybe another "game") to run really laggy things without crashing

### ISSUE THREAD

**Issue by splyfof** [Sequitur-Studios/Cell-Machine-Mystic-Mod#85]

**Comment by itskegnh** [comment]
What exactly is the suggestion? To have a simpler game that doesn't crash?

**Comment by jjblock21** [comment]
I dont get what the suggestion here is, the devs cant just type make-less-laggy an it works like that. How would you suggest making the game less laggy, one could maybe be to optimise the cell cod itsself, but I havent looked into that much, so I dont know how much the devs could speed up there.

**Comment by jjblock21** [comment]
One way to get a higher famerate overall is to disable Anti Aliassing, but that wouldnt help much with the lag when you let a large nuke explode.

**Comment by TheMysticLynx** [comment]
This suggestion is vague. Feel free to open another issue with more details
