### ISSUE TITLE
A way to use the old UI.

### ISSUE THREAD

**Issue by arkanon0** [Sequitur-Studios/Cell-Machine-Mystic-Mod#94]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Please add a way to switch between the new and old UI (no black background, buttons of unequal width, text that says "Cell Machine Mystic Mod" at the top center) in options

**Describe alternatives you've considered**
[None]

**Additional context**
[None]

**Comment by TheMysticLynx** [comment]
This would add unneeded bloat, having 2 main menus?
